version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app_net # ✅ THÊM DÒNG NÀY

  app:
    build: .
    container_name: nestjs_app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${PORT}:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres # ✅ KHÔNG DÙNG db, CHỈ postgres
      POSTGRES_PORT: 5432
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app_net

volumes:
  pg_data:


networks:
  app_net:
    driver: bridge
